//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApoUtilityPrototype1.WpfApp.ServiceProxies
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserAccount",
        Namespace = "http://schemas.datacontract.org/2004/07/ApoUtilityPrototype1.DomainModels")]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string NameField;

        private string PasswordField;

        private int UserIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get { return this.extensionDataField; }
            set { this.extensionDataField = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get { return this.NameField; }
            set { this.NameField = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get { return this.PasswordField; }
            set { this.PasswordField = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get { return this.UserIdField; }
            set { this.UserIdField = value; }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ILoginService")]
    public interface ILoginService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILoginService/IsAuthenticUser",
            ReplyAction = "http://tempuri.org/ILoginService/IsAuthenticUserResponse")]
        bool IsAuthenticUser(UserAccount account);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILoginService/CreateUser",
            ReplyAction = "http://tempuri.org/ILoginService/CreateUserResponse")]
        bool CreateUser(UserAccount user);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : ILoginService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceProxy : System.ServiceModel.ClientBase<ILoginService>, ILoginService
    {

        public LoginServiceProxy()
        {
        }

        public LoginServiceProxy(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public LoginServiceProxy(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LoginServiceProxy(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LoginServiceProxy(System.ServiceModel.Channels.Binding binding,
                                  System.ServiceModel.EndpointAddress remoteAddress) :
                                      base(binding, remoteAddress)
        {
        }

        public bool IsAuthenticUser(UserAccount account)
        {
            return base.Channel.IsAuthenticUser(account);
        }

        public bool CreateUser(UserAccount user)
        {
            return base.Channel.CreateUser(user);
        }
    }
}